#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p \
    /config/log/fail2ban \
    /config/fail2ban/{action.d,filter.d,jail.d}

# copy/update the fail2ban configs from /defaults to /config
cp -R /defaults/fail2ban /config

# symlink fail2ban configs to /config
rm -rf /etc/fail2ban
ln -s /config/fail2ban /etc/fail2ban

# permissions
lsiown -R abc:abc \
    /config
