#!/usr/bin/with-contenv bash
# shellcheck shell=bash

FAIL2BAN_ARGS=()

case "${VERBOSITY:-}" in
-v | -vv | -vvv | -vvvv)
    FAIL2BAN_ARGS+=("${VERBOSITY:-}")
    ;;
*) ;;
esac

FAIL2BAN_ARGS+=("-x" "-f" "start")

exec \
    fail2ban-client "${FAIL2BAN_ARGS[@]}"
